### ISSUE TITLE
ISO Get LMP Fails on 2018-11-04

### ISSUE THREAD

**Issue by kmax12** [kmax12/gridstatus#171]
## Reproduce

```python
import gridstatus

iso = gridstatus.ISONE()
iso.get_lmp(
    date="2018-11-04",
    market="DAY_AHEAD_HOURLY",
)
```

```
AmbiguousTimeError                        Traceback (most recent call last)
Cell In[38], line 4
      1 import gridstatus
      3 iso = gridstatus.ISONE()
----> 4 iso.get_lmp(
      5     date="2018-11-04",
      6     market="DAY_AHEAD_HOURLY",
      7 )

File ~/Documents/isodata/gridstatus/lmp_config.py:26, in lmp_config.__call__.<locals>.wrapper(*args, **kwargs)
     24 if len(args) > 0 and isinstance(args[0], ISOBase):
     25     bound_args = self._verify_bound_args(bound_args)
---> 26     return self._class_method_wrapper(func, bound_args)
     27 else:
     28     # This is a runtime check after method is called.
     29     # Possible improvement: move this to "compile"-time.
     30     raise ValueError("Must be class method on ISOBase")

File ~/Documents/isodata/gridstatus/lmp_config.py:61, in lmp_config._class_method_wrapper(func, bound_args)
     59 instance_args = bound_args.args
     60 instance_kwargs = bound_args.kwargs
---> 61 return func(*instance_args, **instance_kwargs)

File ~/Documents/isodata/gridstatus/decorators.py:78, in support_date_range.__call__.<locals>.wrapped_f(*args, **kwargs)
...
File ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/pandas/_libs/tslibs/tzconversion.pyx:313, in pandas._libs.tslibs.tzconversion.tz_localize_to_utc()

File ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/pandas/_libs/tslibs/tzconversion.pyx:553, in pandas._libs.tslibs.tzconversion._get_dst_hours()

AmbiguousTimeError: There are 3 dst switches when there should only be 1.
```

Likely a problem in the pandas date parsing code. This would be a good first issue.

**Comment by blakeShalom** [comment]
I'll take a look at this one for a first task

**Comment by blakeShalom** [comment]
Ah. 

Pandas assumes that time data is sorted so it can tell when we are going into DST. i.e. times will be going up ascending in the series and then drop the hour go back up again. I'm surprised it works with some of the other DST dates in 2022/2021. It may be that it just infers incorrectly in those cases 🤷 

Because we are looking at hourly data pandas can't infer what the non DST 1a is and what the DST 1a is. But because of the funny 02X hour ending notation, we can be explicit on which one is which. 

I should have a PR up soonish.

**Comment by kmax12** [comment]
we do the groupby location and once that happens, there should be no ambiguity when trying to do the DST infernce.
 
https://github.com/kmax12/gridstatus/blob/88c8082e99be78e3eb1c20e7997a8bc07b69229d/gridstatus/isone.py#L426

I looked more and the issue actually looks to be with the data the ISONE is returning. here is a snippet. you can see there all multiple rows for the same data.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/371792/222595100-ed873d00-c4f7-44e6-8ce6-862654718eb2.png">

i think the actual fix is to just do a drop_duplicates

**Comment by blakeShalom** [comment]
Woof, barked up the wrong tree! hahha. I see, it infers that there is 2 "01:00" in each of the groupings and then can infer that the second is the 01:00 -5UTC. Very cool. I'll add the dedupe code and re-push.

**Comment by kmax12** [comment]
no worries. i also got it wrong in the issue description. issue is with isone, not gridstatus code :)

**Comment by blakeShalom** [comment]
Seems like we may have another data oddity.

After deduping I kept receiving the error and turns out Location ID can have multiple Locations in it. Is there a reason why we groupby Location ID? After grouping by Location I had successful test runs and our difficult DST day worked as well. 

![Capture](https://user-images.githubusercontent.com/2624626/222841469-597d49c2-a8a7-4f39-990d-d8dff82ba635.PNG)

**Comment by kmax12** [comment]
i think only because I assumed Location Id would be unique. If location works, let use that!
